services:
  autovisit-web:
    image: ghcr.io/gusdezup/autovisit-web:latest
    container_name: autovisit-web
    ports:
      - "4567:4567"
    volumes:
      - ./data:/data
    restart: unless-stopped
